In [1]:
import pandas as pd
import numpy as np
!pwd

/Users/Lisa/_MLB_Prediction_capstone/data/Retrosheet_2010_2019

In [2]:
lst = "Date,DoubleHeader,DayOfWeek,VisitingTeam,VisitingTeamLeague,VisitingTeamGameNumber,HomeTeam,HomeTeamLeague,HomeTeamGameNumber,VisitorRunsScored,HomeRunsScore,LengthInOuts,DayNight,CompletionInfo,ForfeitInfo,ProtestInfo,ParkID,Attendence,Duration,VisitorLineScore,HomeLineScore,VisitorAB,VisitorH,VisitorD,VisitorT,VisitorHR,VisitorRBI,VisitorSH,VisitorSF,VisitorHBP,VisitorBB,VisitorIBB,VisitorK,VisitorSB,VisitorCS,VisitorGDP,VisitorCI,VisitorLOB,VisitorPitchers,VisitorER,VisitorTER,VisitorWP,VisitorBalks,VisitorPO,VisitorA,VisitorE,VisitorPassed,VisitorDB,VisitorTP,HomeAB,HomeH,HomeD,HomeT,HomeHR,HomeRBI,HomeSH,HomeSF,HomeHBP,HomeBB,HomeIBB,HomeK,HomeSB,HomeCS,HomeGDP,HomeCI,HomeLOB,HomePitchers,HomeER,HomeTER,HomeWP,HomeBalks,HomePO,HomeA,HomeE,HomePassed,HomeDB,HomeTP,UmpireHID,UmpireHName,Umpire1BID,Umpire1BName,Umpire2BID,Umpire2BName,Umpire3BID,Umpire3BName,UmpireLFID,UmpireLFName,UmpireRFID,UmpireRFName,VisitorManagerID,VisitorManagerName,HomeManagerID,HomeManagerName,WinningPitcherID,WinningPitcherName,LosingPitcherID,LosingPitcherNAme,SavingPitcherID,SavingPitcherName,GameWinningRBIID,GameWinningRBIName,VisitorStartingPitcherID,VisitorStartingPitcherName,HomeStartingPitcherID,HomeStartingPitcherName,VisitorBatting1PlayerID,VisitorBatting1Name,VisitorBatting1Position,VisitorBatting2PlayerID,VisitorBatting2Name,VisitorBatting2Position,VisitorBatting3PlayerID,VisitorBatting3Name,VisitorBatting3Position,VisitorBatting4PlayerID,VisitorBatting4Name,VisitorBatting4Position,VisitorBatting5PlayerID,VisitorBatting5Name,VisitorBatting5Position,VisitorBatting6PlayerID,VisitorBatting6Name,VisitorBatting6Position,VisitorBatting7PlayerID,VisitorBatting7Name,VisitorBatting7Position,VisitorBatting8PlayerID,VisitorBatting8Name,VisitorBatting8Position,VisitorBatting9PlayerID,VisitorBatting9Name,VisitorBatting9Position,HomeBatting1PlayerID,HomeBatting1Name,HomeBatting1Position,HomeBatting2PlayerID,HomeBatting2Name,HomeBatting2Position,HomeBatting3PlayerID,HomeBatting3Name,HomeBatting3Position,HomeBatting4PlayerID,HomeBatting4Name,HomeBatting4Position,HomeBatting5PlayerID,HomeBatting5Name,HomeBatting5Position,HomeBatting6PlayerID,HomeBatting6Name,HomeBatting6Position,HomeBatting7PlayerID,HomeBatting7Name,HomeBatting7Position,HomeBatting8PlayerID,HomeBatting8Name,HomeBatting8Position,HomeBatting9PlayerID,HomeBatting9Name,HomeBatting9Position,AdditionalInfo,AcquisitionInfo"

In [3]:
lst = lst.split(",")

In [4]:
file = '/Users/Lisa/_MLB_Prediction_capstone/data/Retrosheet_2010_2019/retrosheet_season_data/GL2010.TXT'

In [5]:
df = pd.read_csv(file, names=lst)

In [6]:
col_to_drop_1 = ['DoubleHeader', 'DayOfWeek', 'VisitingTeamLeague', 'HomeTeamLeague', 'VisitingTeamGameNumber',
                'HomeTeamGameNumber', 'VisitorRunsScored', 'HomeRunsScore', 'LengthInOuts', 'DayNight', 
                'CompletionInfo', 'ForfeitInfo', 'ProtestInfo', 'ParkID', 'Attendence', 'Duration',
                'VisitorLineScore', 'HomeLineScore', 'VisitorCI', 'HomeCI', 'UmpireHID',
                 'UmpireHName', 'Umpire1BID', 'Umpire1BName','Umpire2BID', 'Umpire2BName','Umpire3BID','Umpire3BName','UmpireLFID',
                 'UmpireLFName','UmpireRFID','UmpireRFName','VisitorManagerID',
                'VisitorManagerName','HomeManagerID','HomeManagerName','WinningPitcherID',
                 'WinningPitcherName','LosingPitcherID','LosingPitcherNAme','SavingPitcherID',
                 'SavingPitcherName', 'GameWinningRBIID', 'GameWinningRBIName', 'AdditionalInfo', 
                 'AcquisitionInfo']

In [17]:
len(col_to_drop_1)

46

In [7]:
df

,Date,DoubleHeader,DayOfWeek,VisitingTeam,VisitingTeamLeague,VisitingTeamGameNumber,HomeTeam,HomeTeamLeague,HomeTeamGameNumber,VisitorRunsScored,...,HomeBatting7Name,HomeBatting7Position,HomeBatting8PlayerID,HomeBatting8Name,HomeBatting8Position,HomeBatting9PlayerID,HomeBatting9Name,HomeBatting9Position,AdditionalInfo,AcquisitionInfo
0,20100404,0,Sun,NYA,AL,1,BOS,AL,1,7,...,J.D. Drew,9,camem001,Mike Cameron,8,scutm001,Marco Scutaro,6,NaN,Y
1,20100405,0,Mon,MIN,AL,1,ANA,AL,1,3,...,Howie Kendrick,4,woodb003,Brandon Wood,5,mathj001,Jeff Mathis,2,NaN,Y
2,20100405,0,Mon,CLE,AL,1,CHA,AL,1,0,...,A.J. Pierzynski,2,teahm001,Mark Teahen,5,ramia003,Alexei Ramirez,6,NaN,Y
3,20100405,0,Mon,DET,AL,1,KCA,AL,1,8,...,Yuniesky Betancourt,6,kendj001,Jason Kendall,2,getzc001,Chris Getz,4,NaN,Y
4,20100405,0,Mon,SEA,AL,1,OAK,AL,1,5,...,Mark Ellis,4,buckt001,Travis Buck,7,pennc001,Cliff Pennington,6,NaN,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2425,20101003,0,Sun,CHN,NL,162,HOU,NL,162,0,...,Humberto Quintero,2,manzt001,Tommy Manzella,6,figun001,Nelson Figueroa,1,NaN,Y
2426,20101003,0,Sun,ARI,NL,162,LAN,NL,162,1,...,Brad Ausmus,2,johnr008,Reed Johnson,7,lillt001,Ted Lilly,1,NaN,Y
2427,20101003,0,Sun,WAS,NL,162,NYN,NL,162,2,...,Josh Thole,2,tejar001,Ruben Tejada,4,pelfm001,Mike Pelfrey,1,NaN,Y
2428,20101003,0,Sun,SDN,NL,162,SFN,NL,162,0,...,Jose Guillen,9,sandp001,Pablo Sandoval,5,sancj002,Jonathan Sanchez,1,NaN,Y
2429,20101003,0,Sun,COL,NL,162,SLN,NL,162,1,...,Matt Pagnozzi,2,ryanb002,Brendan Ryan,6,suppj001,Jeff Suppan,1,NaN,Y

In [8]:
df.iloc[:, 0:20]

,Date,DoubleHeader,DayOfWeek,VisitingTeam,VisitingTeamLeague,VisitingTeamGameNumber,HomeTeam,HomeTeamLeague,HomeTeamGameNumber,VisitorRunsScored,HomeRunsScore,LengthInOuts,DayNight,CompletionInfo,ForfeitInfo,ProtestInfo,ParkID,Attendence,Duration,VisitorLineScore
0,20100404,0,Sun,NYA,AL,1,BOS,AL,1,7,9,51,N,NaN,NaN,NaN,BOS07,37440,226,020300200
1,20100405,0,Mon,MIN,AL,1,ANA,AL,1,3,6,51,N,NaN,NaN,NaN,ANA01,43504,180,020010000
2,20100405,0,Mon,CLE,AL,1,CHA,AL,1,0,6,51,D,NaN,NaN,NaN,CHI12,38935,144,000000000
3,20100405,0,Mon,DET,AL,1,KCA,AL,1,8,4,54,D,NaN,NaN,NaN,KAN06,40052,185,100001600
4,20100405,0,Mon,SEA,AL,1,OAK,AL,1,5,3,54,N,NaN,NaN,NaN,OAK01,30686,167,111000002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2425,20101003,0,Sun,CHN,NL,162,HOU,NL,162,0,4,51,D,NaN,NaN,NaN,HOU03,31105,155,000000000
2426,20101003,0,Sun,ARI,NL,162,LAN,NL,162,1,3,51,D,NaN,NaN,NaN,LOS03,38007,166,000100000
2427,20101003,0,Sun,WAS,NL,162,NYN,NL,162,2,1,84,D,NaN,NaN,NaN,NYC20,30849,254,00001000000001
2428,20101003,0,Sun,SDN,NL,162,SFN,NL,162,0,3,51,D,NaN,NaN,NaN,SFO03,42822,185,000000000
2429,20101003,0,Sun,COL,NL,162,SLN,NL,162,1,6,51,D,NaN,NaN,NaN,STL10,42409,153,000000010

In [9]:
df.iloc[:, 20:40]

,HomeLineScore,VisitorAB,VisitorH,VisitorD,VisitorT,VisitorHR,VisitorRBI,VisitorSH,VisitorSF,VisitorHBP,VisitorBB,VisitorIBB,VisitorK,VisitorSB,VisitorCS,VisitorGDP,VisitorCI,VisitorLOB,VisitorPitchers,VisitorER
0,01001331x,37,12,2,0,2,6,0,0,0,6,0,2,2,0,2,0,9,5,8
1,21001002x,32,7,1,0,1,3,0,1,1,3,0,8,1,0,1,0,7,4,6
2,20201001x,30,4,0,0,0,0,0,0,0,1,0,7,0,0,1,0,4,4,6
3,020020000,39,12,4,0,0,7,0,0,0,2,0,9,0,0,1,0,6,5,4
4,000001200,31,6,2,0,1,5,0,1,0,8,1,8,3,2,1,0,8,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2425,02110000x,33,6,1,0,0,0,0,0,0,3,1,12,0,0,0,0,9,4,3
2426,20000010x,30,4,1,0,0,1,1,0,0,3,0,12,2,0,0,0,6,5,3
2427,00001000000000,46,6,2,0,0,2,0,0,1,6,0,12,1,0,2,0,9,6,1
2428,00200001x,30,4,0,0,0,0,1,0,0,5,1,10,0,0,1,0,9,5,3
2429,00220110x,32,7,1,1,1,1,0,0,0,1,0,9,0,1,0,0,5,4,4

In [10]:
df.iloc[:, 40:60]

,VisitorTER,VisitorWP,VisitorBalks,VisitorPO,VisitorA,VisitorE,VisitorPassed,VisitorDB,VisitorTP,HomeAB,HomeH,HomeD,HomeT,HomeHR,HomeRBI,HomeSH,HomeSF,HomeHBP,HomeBB,HomeIBB
0,8,1,0,24,9,1,1,1,0,34,12,3,1,1,8,0,1,0,4,0
1,6,1,0,24,4,0,0,0,0,33,9,0,0,3,6,0,0,0,3,0
2,6,4,0,24,14,0,0,1,0,28,6,2,0,2,4,0,0,2,5,0
3,4,0,0,27,12,1,0,0,0,35,9,0,0,1,4,1,0,0,2,0
4,3,1,0,27,18,1,0,4,0,28,5,0,0,0,3,0,0,0,7,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2425,3,0,0,24,6,1,0,1,0,31,9,0,1,1,3,1,0,0,2,0
2426,3,0,0,24,10,1,0,2,0,29,8,1,0,1,3,1,0,1,5,1
2427,1,0,0,42,16,1,0,1,0,46,8,1,0,0,0,3,0,1,3,1
2428,3,1,0,24,8,0,0,1,0,34,11,1,1,1,3,0,0,0,1,0
2429,4,1,1,24,11,3,0,1,0,36,11,2,0,0,4,0,0,0,2,0

In [11]:
df.iloc[:, 60:80]

,HomeK,HomeSB,HomeCS,HomeGDP,HomeCI,HomeLOB,HomePitchers,HomeER,HomeTER,HomeWP,HomeBalks,HomePO,HomeA,HomeE,HomePassed,HomeDB,HomeTP,UmpireHID,UmpireHName,Umpire1BID
0,5,0,0,0,0,6,6,7,7,1,0,27,15,0,0,2,0,westj901,Joe West,herna901
1,5,1,0,0,0,6,4,3,3,0,0,27,10,0,0,1,0,mcclt901,Tim McClelland,everm901
2,4,0,1,1,0,5,3,0,0,0,0,27,9,0,0,1,0,darlg901,Gary Darling,hohnb901
3,8,2,0,0,0,7,6,7,7,0,0,27,9,1,0,1,0,rapue901,Ed Rapuano,culbf901
4,6,1,0,4,0,5,5,2,2,1,0,27,9,4,0,1,0,tscht901,Tim Tschida,davib902
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2425,10,1,0,1,0,6,4,0,0,0,0,27,8,0,0,0,0,davib902,Bob Davidson,timmt901
2426,6,0,0,1,0,9,3,1,1,0,0,27,7,0,0,0,0,marqa901,Alfonso Marquez,knigb901
2427,7,0,1,1,0,10,7,2,2,0,0,42,14,0,0,2,0,estam901,Mike Estabrook,kellj901
2428,4,0,0,1,0,8,6,0,0,0,0,27,12,1,0,1,0,mcclt901,Tim McClelland,johna901
2429,4,0,0,1,0,8,3,1,1,1,0,27,8,0,0,1,0,kulpr901,Ron Kulpa,culbf901

In [12]:
df.iloc[:, 80:100]

,Umpire1BName,Umpire2BID,Umpire2BName,Umpire3BID,Umpire3BName,UmpireLFID,UmpireLFName,UmpireRFID,UmpireRFName,VisitorManagerID,VisitorManagerName,HomeManagerID,HomeManagerName,WinningPitcherID,WinningPitcherName,LosingPitcherID,LosingPitcherNAme,SavingPitcherID,SavingPitcherName,GameWinningRBIID
0,Angel Hernandez,schrp901,Paul Schrieber,drakr901,Rob Drake,NaN,(none),NaN,(none),giraj001,Joe Girardi,frant001,Terry Francona,okajh001,Hideki Okajima,parkc002,Chan Ho Park,papej001,Jonathan Papelbon,NaN
1,Mike Everitt,fleta901,Andy Fletcher,johna901,Adrian Johnson,NaN,(none),NaN,(none),gardr001,Ron Gardenhire,sciom001,Mike Scioscia,weavj003,Jered Weaver,bakes002,Scott Baker,fuenb001,Brian Fuentes,matsh001
2,Bill Hohn,drecb901,Bruce Dreckman,estam901,Mike Estabrook,NaN,(none),NaN,(none),actam801,Manny Acta,guilo001,Ozzie Guillen,buehm001,Mark Buehrle,westj001,Jake Westbrook,NaN,(none),konep001
3,Fieldin Culbreth,kulpr901,Ron Kulpa,barkl901,Lance Barksdale,NaN,(none),NaN,(none),leylj801,Jim Leyland,hillt801,Trey Hillman,zumaj001,Joel Zumaya,tejer001,Rob Tejeda,NaN,(none),damoj001
4,Bob Davidson,marqa901,Alfonso Marquez,muchm901,Mike Muchlinski,NaN,(none),NaN,(none),wakad001,Don Wakamatsu,gereb001,Bob Geren,leagb001,Brandon League,ziegb001,Brad Ziegler,aardd001,David Aardsma,kotcc001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2425,Tim Timmons,rackd901,David Rackley,barrl901,Lance Barrett,NaN,(none),NaN,(none),quadm801,Mike Quade,millb101,Brad Mills,figun001,Nelson Figueroa,dempr002,Ryan Dempster,NaN,(none),manzt001
2426,Brian Knight,gibsg901,Greg Gibson,davig901,Gerry Davis,NaN,(none),NaN,(none),gibsk001,Kirk Gibson,torrj101,Joe Torre,lillt001,Ted Lilly,loper001,Rodrigo Lopez,kuo-h001,Hong-Chih Kuo,kempm001
2427,Jeff Kellogg,vanol901,Larry Vanover,carlm901,Mark Carlson,NaN,(none),NaN,(none),riggj801,Jim Riggleman,manuj101,Jerry Manuel,peraj002,Joel Peralta,pereo002,Oliver Perez,batim001,Miguel Batista,maxwj002
2428,Adrian Johnson,fleta901,Andy Fletcher,everm901,Mike Everitt,NaN,(none),NaN,(none),blacb001,Buddy Black,bochb002,Bruce Bochy,sancj002,Jonathan Sanchez,latom001,Mat Latos,wilsb001,Brian Wilson,sancf001
2429,Fieldin Culbreth,cedeg901,Gary Cederstrom,hicke901,Ed Hickox,NaN,(none),NaN,(none),tracj101,Jim Tracy,larut101,Tony LaRussa,suppj001,Jeff Suppan,rogee002,Esmil Rogers,NaN,(none),NaN

In [13]:
df.iloc[:, 100:120]

,GameWinningRBIName,VisitorStartingPitcherID,VisitorStartingPitcherName,HomeStartingPitcherID,HomeStartingPitcherName,VisitorBatting1PlayerID,VisitorBatting1Name,VisitorBatting1Position,VisitorBatting2PlayerID,VisitorBatting2Name,VisitorBatting2Position,VisitorBatting3PlayerID,VisitorBatting3Name,VisitorBatting3Position,VisitorBatting4PlayerID,VisitorBatting4Name,VisitorBatting4Position,VisitorBatting5PlayerID,VisitorBatting5Name,VisitorBatting5Position
0,(none),sabac001,CC Sabathia,beckj002,Josh Beckett,jeted001,Derek Jeter,6,johnn001,Nick Johnson,10,teixm001,Mark Teixeira,3,rodra001,Alex Rodriguez,5,canor001,Robinson Cano,4
1,Hideki Matsui,bakes002,Scott Baker,weavj003,Jered Weaver,spand001,Denard Span,8,hudso001,Orlando Hudson,4,mauej001,Joe Mauer,2,mornj001,Justin Morneau,3,cuddm001,Michael Cuddyer,9
2,Paul Konerko,westj001,Jake Westbrook,buehm001,Mark Buehrle,cabra002,Asdrubal Cabrera,6,sizeg001,Grady Sizemore,8,choos001,Shin-Soo Choo,9,hafnt001,Travis Hafner,10,peraj001,Jhonny Peralta,5
3,Johnny Damon,verlj001,Justin Verlander,greiz001,Zack Greinke,jacka001,Austin Jackson,8,damoj001,Johnny Damon,7,ordom001,Magglio Ordonez,9,cabrm001,Miguel Cabrera,3,guilc001,Carlos Guillen,10
4,Casey Kotchman,hernf002,Felix Hernandez,sheeb001,Ben Sheets,suzui001,Ichiro Suzuki,9,figgc001,Chone Figgins,4,kotcc001,Casey Kotchman,3,bradm001,Milton Bradley,7,grifk002,Ken Griffey,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2425,Tommy Manzella,dempr002,Ryan Dempster,figun001,Nelson Figueroa,dewib001,Blake DeWitt,4,barnd001,Darwin Barney,6,byrdm001,Marlon Byrd,8,ramia001,Aramis Ramirez,5,nadyx001,Xavier Nady,3
2426,Matt Kemp,loper001,Rodrigo Lopez,lillt001,Ted Lilly,abret001,Tony Abreu,5,ojeda001,Augie Ojeda,6,ryalr001,Rusty Ryal,3,alleb001,Brandon Allen,7,rober002,Ryan Roberts,4
2427,Justin Maxwell,hernl003,Livan Hernandez,pelfm001,Mike Pelfrey,espid001,Danny Espinosa,4,morgn001,Nyjer Morgan,8,desmi001,Ian Desmond,6,dunna001,Adam Dunn,3,bernr001,Roger Bernadina,7
2428,Freddy Sanchez,latom001,Mat Latos,sancj002,Jonathan Sanchez,denoc001,Chris Denorfia,8,ecksd001,David Eckstein,4,tejam001,Miguel Tejada,6,gonza003,Adrian Gonzalez,3,ludwr001,Ryan Ludwick,9
2429,(none),rogee002,Esmil Rogers,suppj001,Jeff Suppan,fowld001,Dexter Fowler,8,barmc001,Clint Barmes,6,mckem001,Michael McKenry,2,stewi001,Ian Stewart,5,iannc001,Chris Iannetta,3

In [14]:
df.iloc[:, 120:140]

,VisitorBatting6PlayerID,VisitorBatting6Name,VisitorBatting6Position,VisitorBatting7PlayerID,VisitorBatting7Name,VisitorBatting7Position,VisitorBatting8PlayerID,VisitorBatting8Name,VisitorBatting8Position,VisitorBatting9PlayerID,VisitorBatting9Name,VisitorBatting9Position,HomeBatting1PlayerID,HomeBatting1Name,HomeBatting1Position,HomeBatting2PlayerID,HomeBatting2Name,HomeBatting2Position,HomeBatting3PlayerID,HomeBatting3Name
0,posaj001,Jorge Posada,2,granc001,Curtis Granderson,8,swisn001,Nick Swisher,9,gardb001,Brett Gardner,7,ellsj001,Jacoby Ellsbury,7,pedrd001,Dustin Pedroia,4,martv001,Victor Martinez
1,kubej002,Jason Kubel,10,yound003,Delmon Young,7,hardj003,J.J. Hardy,6,puntn001,Nick Punto,5,aybae001,Erick Aybar,6,abreb001,Bobby Abreu,9,huntt001,Torii Hunter
2,lapom001,Matt LaPorta,3,grudm001,Mark Grudzielanek,4,marsl001,Lou Marson,2,branm003,Michael Brantley,7,pierj002,Juan Pierre,7,beckg001,Gordon Beckham,4,quenc001,Carlos Quentin
3,ingeb001,Brandon Inge,5,lairg001,Gerald Laird,2,sizes001,Scott Sizemore,4,evera001,Adam Everett,6,dejed001,David DeJesus,9,podss001,Scott Podsednik,7,butlb003,Billy Butler
4,lopej003,Jose Lopez,5,gutif001,Franklin Gutierrez,8,johnr009,Rob Johnson,2,wilsj002,Jack Wilson,6,davir003,Rajai Davis,8,bartd001,Daric Barton,3,sweer001,Ryan Sweeney
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2425,soria001,Alfonso Soriano,7,snydb002,Brad Snyder,9,hillk002,Koyie Hill,2,dempr002,Ryan Dempster,1,bogub001,Brian Bogusevic,8,keppj001,Jeff Keppinger,4,pench001,Hunter Pence
2426,parrg001,Gerardo Parra,9,schmk001,Konrad Schmidt,2,gillc002,Cole Gillespie,8,loper001,Rodrigo Lopez,1,furcr001,Rafael Furcal,6,carrj001,Jamey Carroll,4,ethia001,Andre Ethier
2427,rodri001,Ivan Rodriguez,2,harrw001,Willie Harris,9,gonza005,Alberto Gonzalez,5,hernl003,Livan Hernandez,1,reyej001,Jose Reyes,6,felij002,Jesus Feliciano,9,wrigd002,David Wright
2428,torry001,Yorvit Torrealba,2,hairs001,Scott Hairston,7,headc001,Chase Headley,5,latom001,Mat Latos,1,torra001,Andres Torres,8,sancf001,Freddy Sanchez,4,huffa001,Aubrey Huff
2429,smits002,Seth Smith,9,paytj001,Jay Payton,7,nelsc001,Chris Nelson,4,rogee002,Esmil Rogers,1,schus001,Skip Schumaker,4,winnr001,Randy Winn,9,pujoa001,Albert Pujols

In [15]:
df.iloc[:, 140:160]

,HomeBatting3Position,HomeBatting4PlayerID,HomeBatting4Name,HomeBatting4Position,HomeBatting5PlayerID,HomeBatting5Name,HomeBatting5Position,HomeBatting6PlayerID,HomeBatting6Name,HomeBatting6Position,HomeBatting7PlayerID,HomeBatting7Name,HomeBatting7Position,HomeBatting8PlayerID,HomeBatting8Name,HomeBatting8Position,HomeBatting9PlayerID,HomeBatting9Name,HomeBatting9Position,AdditionalInfo
0,2,youkk001,Kevin Youkilis,3,ortid001,David Ortiz,10,belta001,Adrian Beltre,5,drewj001,J.D. Drew,9,camem001,Mike Cameron,8,scutm001,Marco Scutaro,6,NaN
1,8,matsh001,Hideki Matsui,10,morak001,Kendrys Morales,3,rivej001,Juan Rivera,7,kendh001,Howie Kendrick,4,woodb003,Brandon Wood,5,mathj001,Jeff Mathis,2,NaN
2,9,konep001,Paul Konerko,3,kotsm001,Mark Kotsay,10,riosa002,Alex Rios,8,piera001,A.J. Pierzynski,2,teahm001,Mark Teahen,5,ramia003,Alexei Ramirez,6,NaN
3,3,ankir001,Rick Ankiel,8,guilj001,Jose Guillen,10,bloow001,Willie Bloomquist,5,betay001,Yuniesky Betancourt,6,kendj001,Jason Kendall,2,getzc001,Chris Getz,4,NaN
4,9,kouzk001,Kevin Kouzmanoff,5,suzuk001,Kurt Suzuki,2,chave001,Eric Chavez,10,ellim001,Mark Ellis,4,buckt001,Travis Buck,7,pennc001,Cliff Pennington,6,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2425,9,lee-c001,Carlos Lee,7,johnc003,Chris Johnson,5,wallb001,Brett Wallace,3,quinh001,Humberto Quintero,2,manzt001,Tommy Manzella,6,figun001,Nelson Figueroa,1,NaN
2426,9,kempm001,Matt Kemp,8,lonej001,James Loney,3,blakc001,Casey Blake,5,ausmb001,Brad Ausmus,2,johnr008,Reed Johnson,7,lillt001,Ted Lilly,1,NaN
2427,5,davii001,Ike Davis,3,pagaa001,Angel Pagan,8,dudal001,Lucas Duda,7,tholj001,Josh Thole,2,tejar001,Ruben Tejada,4,pelfm001,Mike Pelfrey,1,NaN
2428,3,poseb001,Buster Posey,2,burrp001,Pat Burrell,7,uribj002,Juan Uribe,6,guilj001,Jose Guillen,9,sandp001,Pablo Sandoval,5,sancj002,Jonathan Sanchez,1,NaN
2429,3,hollm001,Matt Holliday,7,rasmc001,Colby Rasmus,8,descd001,Daniel Descalso,5,pagnm001,Matt Pagnozzi,2,ryanb002,Brendan Ryan,6,suppj001,Jeff Suppan,1,NaN

In [16]:
df.iloc[:, 160:]

     AcquisitionInfo
0                  Y
1                  Y
2                  Y
3                  Y
4                  Y
...              ...
2425               Y
2426               Y
2427               Y
2428               Y
2429               Y

[2430 rows x 1 columns]